version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    TF_PATH: "/usr/local/bin"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - set -e
      - echo "Installing Terraform ${TF_VERSION}..."
      - curl -sS -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip -d "${TF_PATH}"
      - rm terraform.zip
      - chmod +x "${TF_PATH}/terraform"
      - terraform version
      - aws --version

  pre_build:
    commands:
      - echo "Running terraform init..."
      - terraform init -input=false

  build:
    commands:
      - echo "Validating configs..."
      - terraform validate
      - echo "Creating plan..."
      - terraform plan -out=tfplan.out

  
artifacts:
  files:
    - tfplan.out
  discard-paths: no
